"""Add head_ref_github_graphql_id

Revision ID: d1c6ec4ab3fa
Revises: f3b910a409d0
Create Date: 2026-04-05 16:47:22.177692

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d1c6ec4ab3fa"
down_revision: Union[str, Sequence[str], None] = "f3b910a409d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pull_request",
        sa.Column(
            "head_ref_github_graphql_id",
            sa.String(length=255),
            server_default="",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pull_request", "head_ref_github_graphql_id")
    # ### end Alembic commands ###
